# Generated by Django 3.2.11 on 2022-01-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='nik',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
