# Generated by Django 3.2.11 on 2022-01-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_wallet_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nik',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
